### ISSUE TITLE
Code Search Out of Memory

### ISSUE THREAD

**Issue by powturns** [colin353/universe#14]
Thanks for the tool!

When attempting to index the android source code:
https://source.android.com/setup/build/downloading

Code search exhausts my system memory after consuming ~20GB

**Comment by colin353** [comment]
Hey Dustin, thanks for the feedback. I'll try to reproduce and put together a fix. 

Just guessing, but the execution planner here: https://search.colinmerkel.xyz/plume/lib.rs#L36 is trying to maintain the definition extraction collection completely in memory instead of on disk. At least that's my theory, I'll look into it

Will keep this thread updated

**Comment by colin353** [comment]
Hey, sorry this took so long, but I did finally fix the execution planner. There was a bug that made it decide to keep things in memory in some circumstancesm, and I changed it to prefer disk. This means it uses more disk space when running the indexer but much less memory.

I haven't tried it on your specific repository but I think it should make a difference. 

For reference the fix is in https://github.com/colin353/universe/commit/fb053c9cee32e574e43d609dba413c8e0fe851d8

I'm going to close this for now, let me know if you see this come up again!
